### ISSUE TITLE
svtk resolve StopIteration

### ISSUE THREAD

**Issue by ghzhaole** [talkowski-lab/svtk#102]
When running svtk resolve, the following error reported:
```
Traceback (most recent call last):
  File "/home/luohx/work/SV/gnomad_sv_code/svtk/svtk/cli/resolve.py", line 231, in resolve_complex_sv
    cpx = ComplexSV(cluster, cytobands, mei_bed, SR_only_cutoff)
  File "/home/luohx/work/SV/gnomad_sv_code/svtk/svtk/cxsv/complex_sv.py", line 38, in __init__
    self.resolve(SR_only_cutoff=SR_only_cutoff)
  File "/home/luohx/work/SV/gnomad_sv_code/svtk/svtk/cxsv/complex_sv.py", line 82, in resolve
    self.resolve_translocation()
  File "/home/luohx/work/SV/gnomad_sv_code/svtk/svtk/cxsv/complex_sv.py", line 278, in resolve_translocation
    armA, armB = get_arms(plus, self.cytobands)
  File "/home/luohx/work/SV/gnomad_sv_code/svtk/svtk/cxsv/complex_sv.py", line 650, in get_arms
    return _get_arm(regionA), _get_arm(regionB)
  File "/home/luohx/work/SV/gnomad_sv_code/svtk/svtk/cxsv/complex_sv.py", line 643, in _get_arm
    arm = next(cytobands.fetch(region))
  File "pysam/libctabix.pyx", line 673, in pysam.libctabix.TabixIterator.__next__
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/luohx/software/anaconda3/envs/cromwell/bin/svtk", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/luohx/work/SV/gnomad_sv_code/svtk/scripts/svtk", line 67, in <module>
    main()
  File "/home/luohx/work/SV/gnomad_sv_code/svtk/scripts/svtk", line 64, in main
    getattr(cli, command)(sys.argv[2:])
  File "/home/luohx/work/SV/gnomad_sv_code/svtk/svtk/cli/resolve.py", line 481, in main
    for record in resolve_complex_sv(vcf, cytobands, disc_pairs, mei_bed, args.prefix,
RuntimeError: generator raised StopIteration
```

Here is the command:
```
bash mantatloccheck.sh std_000.manta.100001.vcf.gz 100001.disc.txt.gz 100001 hg38_v0_sv-resources_resources_v1_mei_hg38.bed.gz hg38_v0_sv-resources_resources_v1_cytobands_hg38.bed.gz
```

The error is produced by capturing the wrong region that dosen't match the cytoband file.

I check the error line of std_000.manta.100001.vcf.gz file:
```
#CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  100001
chr1    88507127    manta_100001_248    N   [chr17:33736831[N   .   PASS    END=33736831;SVTYPE=BND;CHR2=chr17;STRANDS=--;SVLEN=-1;ALGORITHMS=manta;EVIDENCE=PE;MEMBERS=manta_100001_248	GT:manta    0/1:1
chr1    88507142    manta_100001_249    N   N]chr17:33737644]   .   PASS    END=33737644;SVTYPE=BND;CHR2=chr17;STRANDS=++;SVLEN=-1;ALGORITHMS=manta;EVIDENCE=PE;MEMBERS=manta_100001_249	GT:manta    0/1:1
```

The pos "33737644" is supposed to be extracted with chr17 but "88507142" is wrongly extracted which causes the bug. 

Could you please help me out with this issue? 
Thanks in advance!

**Comment by RCollins13** [comment]
Hi,

Thanks for this bug report. This repo is no longer maintained, as svtk has been migrated over to https://github.com/broadinstitute/gatk-sv.

Can you try running your above command with the most up-to-date version of svtk provided in the GATK-SV repo? If the error persists, filing an issue in the GATK-SV repo will help get this problem resolved.

Thanks,
Ryan
