### ISSUE TITLE
Annotate error

### ISSUE THREAD

**Issue by kpjonsson** [talkowski-lab/svtk#95]
Great tool, but I'm having some problems running the annotate module, which I can't figure out whether it's due to the input files or not. See below my command and the error message:
```shell
> svtk annotate --gencode gencode.v31lift37.basic.annotation.protein_coding.gtf input.vcf input.annot.vcf
Traceback (most recent call last):
  File "/usr/local/bin/svtk", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/svtk/scripts/svtk", line 67, in <module>
    main()
  File "/svtk/scripts/svtk", line 64, in main
    getattr(cli, command)(sys.argv[2:])
  File "/svtk/svtk/cli/annotate.py", line 82, in main
    anno.annotate_vcf(vcf, gencode, noncoding, args.annotated_vcf)
  File "/svtk/svtk/annotation/annotate.py", line 143, in annotate_vcf
    effects = annotate(sv, gencode, noncoding)
  File "/svtk/svtk/annotation/annotate.py", line 74, in annotate
    coding_anno = None if gencode is None else annotate_gencode(sv, gencode)
  File "/svtk/svtk/annotation/annotate.py", line 21, in annotate_gencode
    effects = classify_effect(hits)
  File "/svtk/svtk/annotation/classify_effect.py", line 183, in classify_effect
    effects['effect'] = effects.apply(_apply_classify, axis=1)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 6913, in apply
    return op.get_result()
  File "/usr/local/lib/python3.7/site-packages/pandas/core/apply.py", line 186, in get_result
    return self.apply_standard()
  File "/usr/local/lib/python3.7/site-packages/pandas/core/apply.py", line 292, in apply_standard
    self.apply_series_generator()
  File "/usr/local/lib/python3.7/site-packages/pandas/core/apply.py", line 321, in apply_series_generator
    results[i] = self.f(v)
  File "/svtk/svtk/annotation/classify_effect.py", line 181, in _apply_classify
    return classify_disrupt(element_hit, svtype)
  File "/svtk/svtk/annotation/classify_effect.py", line 164, in classify_disrupt
    return classify_inv(disrupt_dict)
  File "/svtk/svtk/annotation/classify_effect.py", line 90, in classify_inv
    elif ('BOTH-INSIDE' in disrupt_dict['gene'] or
KeyError: ('gene', 'occurred at index 3')
```

_Edit:_ It seems to be something in `input.vcf`, since it works fine on another VCF file I tried the same command with.

**Comment by kpjonsson** [comment]
Fixed by manipulating the GTF.
